name: data
env:
  VACCINATION_SITES: 'https://www.england.nhs.uk/coronavirus/wp-content/uploads/sites/52/2021/01/List-of-vaccination-sites-17-November-2021.xlsx'
on:
  schedule:
    - cron: 0 0 * * *
  workflow_dispatch: {}
  push:
    paths:
      - .github/workflows/flat.yml
      - ./scripts/extract-vaccination-sites.ts
jobs:
  scheduled:
    runs-on: ubuntu-latest
    steps:
      - name: Setup deno
        uses: denoland/setup-deno@main
        with:
          deno-version: v1.x
      - name: Check out repo
        uses: actions/checkout@v2
      - name: Fetch data
        uses: githubocto/flat@v3
        with:
          http_url: '${{ env.VACCINATION_SITES }}'
          downloaded_filename: data/vaccination-sites.xlsx
          postprocess: ./scripts/extract-vaccination-sites.ts
